import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            nome: 'Iuri',
            email: 'iuri@hotmail.com',
            senha: bcrypt.hashSync('iuri', 8),
            ehAdmin: true,
        },
        {
            nome: 'Salete',
            email: 'salete@hotmail.com',
            senha: bcrypt.hashSync('salete', 8),
            ehAdmin: false,
        },
    ],
    produtos: [
        {
            nome: 'PlayStation 5',
            categoria: 'Consoles',
            imagem: '/imagens/Ps5.jpg',
            preco: 4700,
            temStock: 1,
            marca: 'Sony',
            avaliacao: 5,
            numAvaliacoes: 45,
            descricao: 'Play Has No Limits... Jogar Não Tem Limites... PlayStation®5 O console PS5 oferece novas possibilidades de jogabilidade que você nunca imaginou.',
        },
        {
            nome: 'Demons Souls',
            categoria: 'Jogos',
            imagem: '/imagens/ds.png',
            preco: 350,
            temStock: 4,
            marca: 'BluePonint',
            avaliacao: 5,
            numAvaliacoes: 36,
            descricao: 'Em sua busca por poder, o 12º Rei de Boletaria, Rei Allant, canalizou as ancestrais Artes da Alma, despertando um demônio do alvorecer dos tempos, o Ancião.',
        },
        {
            nome: 'Returnal',
            categoria: 'Jogos',
            imagem: '/imagens/returnal.png',
            preco: 350,
            temStock: 3,
            marca: 'Seila',
            avaliacao: 3.5,
            numAvaliacoes: 15,
            descricao: 'Após uma queda forçada em um planeta alienígena que muda de forma, Selene se vê lutando com unhas e dentes pela sobrevivência. Ela é derrotada várias vezes e forçada a reiniciar sua jornada toda vez que morre.',
        },
        {
            nome: 'Mortal Kombat 11',
            categoria: 'Jogos',
            imagem: '/imagens/mk.png',
            preco: 349,
            temStock: 4,
            marca: 'WB Games',
            avaliacao: 3,
            numAvaliacoes: 10,
            descricao: 'Mortal Kombat XI combina uma apresentação cinemática única com uma jogabilidade totalmente nova. Os jogadores podem escolher pela primeira vez diversas variantes de cada personagem, afetando tanto a estratégia como o estilo de luta.',
        },
        {
            nome: 'Xbox Series S',
            categoria: 'Consoles',
            imagem: '/imagens/xbox.jpg',
            preco: 5200,
            temStock: 500,
            marca: 'Microsoft',
            avaliacao: 1.5,
            numAvaliacoes: 20,
            descricao: 'Apresentamos o Xbox Series S, o menor e mais elegante Xbox de todos tempos. Experimente a velocidade e desempenho de um console de próxima geração totalmente digital.',
        },
        {
            nome: 'Halo',
            categoria: 'Jogos',
            imagem: '/imagens/halo.png',
            preco: 69,
            temStock: 4,
            marca: 'Microsoft',
            avaliacao: 1.5,
            numAvaliacoes: 10,
            descricao: 'Halo 5: Guardians é um jogo de tiro na primeira pessoa (first-person shooter), a história sequência de Halo 4, onde uma força misteriosa e implacável ameaça a galáxia, enquanto o Master Chief está desaparecido e sua lealdade é questionada.',
        },
        {
            nome: 'Sekiro',
            categoria: 'Jogos',
            imagem: '/imagens/sekiro.png',
            preco: 249,
            temStock: 4,
            marca: 'FromSoftware',
            avaliacao: 5,
            numAvaliacoes: 15,
            descricao: 'Trilhe o caminho da vingança nesta aventura inédita da FromSoftware, os criadores da série Dark Souls. Em Sekiro: Shadows Die Twice, você é o "lobo de um braço só", um guerreiro desfigurado e desgraçado, resgatado da beira da morte. Destinado a proteger um jovem senhor descendente de uma antiga linhagem, você é alvo de muitos inimigos cruéis, incluindo o perigoso clã Ashina. E, após a captura do jovem senhor, nada impedirá sua jornada arriscada para retomar sua honra, nem mesmo a morte. Explore o Japão do final dos anos 1500, no Período Sengoku, enquanto enfrenta inimigos épicos em um mundo sombrio e distorcido. Use um arsenal de próteses letais e habilidades ninjas poderosas ao mesmo tempo, alternando furtividade, travessia vertical e combate direto em um confronto visceral. Vingue-se. Restaure sua honra. Mate com astúcia.',
        },
        {
            nome: 'Gabinete PC Gamer',
            categoria: 'Computadores',
            imagem: '/imagens/pcgamer.jpg',
            preco: 3900,
            temStock: 0,
            marca: 'Cichau',
            avaliacao: 3,
            numAvaliacoes: 3,
            descricao: 'Conheça o gabinete Cichau Gaming Komor, com PSU cover e frente facilmente removível e lateral em vidro temperado 4mm, é o ideal para fazer o update no seu setup gamer.',
        },
        {
            nome: 'Produto teste 1',
            categoria: 'Teste',
            imagem: '/imagens/prod1.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 2',
            categoria: 'Teste',
            imagem: '/imagens/prod2.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 3',
            categoria: 'Teste',
            imagem: '/imagens/prod3.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 4',
            categoria: 'Teste',
            imagem: '/imagens/prod4.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 5',
            categoria: 'Teste',
            imagem: '/imagens/prod5.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 6',
            categoria: 'Teste',
            imagem: '/imagens/prod6.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 7',
            categoria: 'Teste',
            imagem: '/imagens/prod7.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 8',
            categoria: 'Teste',
            imagem: '/imagens/prod8.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 9',
            categoria: 'Teste',
            imagem: '/imagens/prod9.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
        {
            nome: 'Produto teste 10',
            categoria: 'Teste',
            imagem: '/imagens/prod10.png',
            preco: 40,
            temStock: 12,
            marca: 'Teste',
            avaliacao: 4,
            numAvaliacoes: 3,
            descricao: 'Teste de produto, não comprar.',
        },
    ],
};

export default data;