export const CARRINHO_ADD_ITEM = 'CARRINHO_ADD_ITEM';
export const CARRINHO_DELETE_ITEM = 'CARRINHO_DELETE_ITEM';

export const CARRINHO_SAVE_SHIPPING = 'CARRINHO_SAVE_SHIPPING';
export const CARRINHO_SAVE_METODO_PAGAMENTO = 'CARRINHO_SAVE_METODO_PAGAMENTO';