export const REQUISICAO_LISTA_PRODUTO = 'REQUISICAO_LISTA_PRODUTO';
export const SUCESSO_LISTA_PRODUTO = 'SUCESSO_LISTA_PRODUTO';
export const FALHA_LISTA_PRODUTO = 'FALHA_LISTA_PRODUTO';

export const REQUISICAO_DETALHES_PRODUTO = 'REQUISICAO_DETALHES_PRODUTO';
export const SUCESSO_DETALHES_PRODUTO = 'SUCESSO_DETALHES_PRODUTO';
export const FALHA_DETALHES_PRODUTO = 'FALHA_DETALHES_PRODUTO';