export const USUARIO_SIGNIN_REQUEST = 'USUARIO_SIGNIN_REQUEST';
export const USUARIO_SIGNIN_SUCESS = 'USUARIO_SIGNIN_SUCESS';
export const USUARIO_SIGNIN_FAIL = 'USUARIO_SIGNIN_FAIL';
export const USUARIO_SIGNOUT = 'USUARIO_SIGNOUT';

export const USUARIO_REGISTER_REQUEST = 'USUARIO_REGISTER_REQUEST';
export const USUARIO_REGISTER_SUCESS = 'USUARIO_REGISTER_SUCESS';
export const USUARIO_REGISTER_FAIL = 'USUARIO_REGISTER_FAIL';